### ISSUE TITLE
Deadlock in FastConsoleSink.Dispose

### ISSUE THREAD

**Issue by Firebie** [manigandham/serilog-sinks-fastconsole#3]
In my WinForms app I have a deadlock on line 'WriteQueueWorker.GetAwaiter().GetResult();'
I am using ver. 1.3.2 of FastConsoleSink

**Comment by manigandham** [comment]
Hi, what .NET framework/version are you using?

**Comment by Firebie** [comment]
Hi,
it is .net 4.6.2.

**Comment by manigandham** [comment]
I released 1.4.0 today: https://www.nuget.org/packages/Serilog.Sinks.FastConsole/

can you try that? are you manually closing Serilog? How is the deadlock happening?

**Comment by Firebie** [comment]
Yes, I am doing it manually, but in this example it is a WinForms app, which has no console:
```cs
void TestFunc()
{
  using var logger =
    new LoggerConfiguration()
    ...
    .WriteTo.Async(
      c =>
      {
        ...
        c.FastConsole(new FastConsoleSinkOptions { UseJson = false });
        ...
      })
    .CreateLogger();
    
    ...
    logger.Information($"Query id: {QueryId}");
    ....
}
```

**Comment by Firebie** [comment]
The issue is still there in 1.4.0 (_writeQueueWorker.Dispose();):
![Deadlock](https://user-images.githubusercontent.com/231808/115984667-fe0ca200-a5b0-11eb-828a-cf383b83de73.png)

**Comment by Firebie** [comment]
Another:
![Deadlock 2](https://user-images.githubusercontent.com/231808/115984706-301e0400-a5b1-11eb-8d9b-5b625c900d08.png)

**Comment by Firebie** [comment]
Can it be related to a fact that there is no actual console?

**Comment by manigandham** [comment]
There should still be a console output stream (for example you can still use `Console.WriteLine` and see the output in Visual Studio).

I believe the issue is due to the `SynchronizationContext` in .NET Framework and using async/await so I added `ConfigureAwait(false)` to all async calls. Can you try the latest release: https://www.nuget.org/packages/Serilog.Sinks.FastConsole/1.4.1

If that doesn't work then I'll need some kind of minimal app to reproduce the issue...

**Comment by Firebie** [comment]
1.4.1 works
Thank you
